name: Local CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop old container
      run: |
        $container = docker ps -a --format "{{.Names}}" | Select-String "^nginx$"
        if ($container) {
          docker stop nginx
          docker rm nginx
        } else {
          Write-Output "No existing container found"
        }

    - name: Build Docker image
      run: docker build -t nginx-local .

    - name: Run container
      run: docker run -d -p 80:80 --name nginx nginx-local